version: '3'


services:
  tasksapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: tasksapp
    container_name: tasksapp
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: tasksdb
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      API_PREFIX: ${API_PREFIX}
      API_VERSION: ${API_VERSION}
      API_PORT: ${API_PORT}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: postgres:15.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: tasksdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
